
services:
###> doctrine/doctrine-bundle ###
  php:
    image: php:8.2-apache
    container_name: php82
    ports: 8741:80
    volumes:
      - .:/var/www/html
    build:
      context: .
      dockerfile: DockerFile
  database:
    image: mysql:8.0
    container_name: mysql80
    ports:
      - 3307:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - ./mysql:/var/lib/mysql
    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      restart: always
      container_name: phpmyadmin
      depends_on:
        - db
      environment:
        PMA_ARBITRARY: 1
        PMA_HOST: db
        PMA_USER: root
        PMA_PASSWORD: ''
      ports:
        - 8888:80
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###
