
services:

  php:
      image: php:8.2-apache
      container_name: php82
      ports: 8741:80
      volumes:
        - .:/var/www/html
        - ./docker/php/vhosts:/etc/apache2/sites-enabled
      build:
        context: .
        dockerfile: DockerFile
      networks:
        - docker-symfony-test
  db:
      image: mysql:8.0
      container_name: mysql80
      ports:
        - 3307:3306
      environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      volumes:
        - ./mysql:/var/lib/mysql
      networks:
        - docker-symfony-test
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      restart: always
      container_name: phpmyadmin
      depends_on:
        - db
      environment:
        PMA_ARBITRARY: 1
        PMA_HOST: db
        PMA_USER: root
        PMA_PASSWORD: ''
      ports:
        - 8888:80
      networks:
        - docker-symfony-test

networks:
  docker-symfony-test: